### ISSUE TITLE
buildfix

### ISSUE THREAD

**Issue by r-sukanya** [Rostlab/JS18_ProjectA_Group1#83]

**Comment by syxolk** [comment]
For documentation purposes:

Running `npm install` locally with `node -v` v8.11.0 and `npm -v` 5.6.0 resulted in this error:

```
13805 verbose stack Error: sha512-RwJOS9ZAGhz6jQwQf8pj8SojydXhupXjZuXgiXP3BFbSZmuXUzPGA5LJN8QOxVgCv5g5St94DdjIJVHgCsIaUQ== integrity checksum failed when using sha512: wanted sha512-RwJOS9ZAGhz6jQwQf8pj8SojydXhupXjZuXgiXP3BFbSZmuXUzPGA5LJN8QOxVgCv5g5St94DdjIJVHgCsIaUQ== but got sha512-l+uhXf1YAmy1W2aDYsjivKnr2ljU2mBEd1sp39QPR4HMAsEnxTvLMHlofKvqCWZLk5gk2vMvyvcI3A5sL/cTEw==. (45473 bytes)
13805 verbose stack     at Transform.on (/usr/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
13805 verbose stack     at emitNone (events.js:111:20)
13805 verbose stack     at Transform.emit (events.js:208:7)
13805 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
13805 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
13805 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
13806 verbose cwd /home/dev/JS18_ProjectA_Group1
13807 verbose Linux 4.4.0-78-generic
13808 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
13809 verbose node v8.11.0
13810 verbose npm  v5.6.0
13811 error code EINTEGRITY
13812 error sha512-RwJOS9ZAGhz6jQwQf8pj8SojydXhupXjZuXgiXP3BFbSZmuXUzPGA5LJN8QOxVgCv5g5St94DdjIJVHgCsIaUQ== integrity checksum failed when using sha512: wanted sha512-RwJOS9ZAGhz6jQwQf8pj8SojydXhupXjZuXgiXP3BFbSZmuXUzPGA5LJN8QOxVgCv5g5St94DdjIJVHgCsIaUQ== but got sha512-l+uhXf1YAmy1W2aDYsjivKnr2ljU2mBEd1sp39QPR4HMAsEnxTvLMHlofKvqCWZLk5gk2vMvyvcI3A5sL/cTEw==. (45473 bytes)
13813 verbose exit [ 1, true ]
```

After updating `npm` to 5.8.0 and deleting `node_modules`, the error disappeared. It's unclear what exactly caused the error.

**Comment by syxolk** [comment]
I just found this diff in my `package-lock.json`:

```
     "js18_projectb_group3": {
       "version": "https://github.com/Rostlab/JS18_ProjectB_Group3/tarball/develop",
-      "integrity": "sha512-RwJOS9ZAGhz6jQwQf8pj8SojydXhupXjZuXgiXP3BFbSZmuXUzPGA5LJN8QOxVgCv5g5St94DdjIJVHgCsIaUQ==",
+      "integrity": "sha512-l+uhXf1YAmy1W2aDYsjivKnr2ljU2mBEd1sp39QPR4HMAsEnxTvLMHlofKvqCWZLk5gk2vMvyvcI3A5sL/cTEw==",
       "requires": {
```

Whenever group 3 updates their code, the SHA512 also changes but that is not reflected in your `package-lock.json`.

**Comment by syxolk** [comment]
I think its better if you would change your `package.json` to reference a specific commit:
```
"js18_projectb_group3": "git+https://github.com/Rostlab/JS18_ProjectB_Group3#90a72531679998b335f8cf1db818efa4239800b1",
```
instead of
```
"js18_projectb_group3": "https://github.com/Rostlab/JS18_ProjectB_Group3/tarball/develop",
```

**Comment by r-sukanya** [comment]
then our code will not show their changes post this specific commit, right ? and we need to keep updating the commit reference ?

**Comment by syxolk** [comment]
Yep, that might be a problem.
