### ISSUE TITLE
Fix azure deploymnet

### ISSUE THREAD

**Issue by sebmarste** [Rostlab/JS18_ProjectA_Group1#99]

**Comment by sebmarste** [comment]
```
2018-04-11T01:16:23.013591824Z > nlp-graph@1.0.0 start /home/site/wwwroot
2018-04-11T01:16:23.013600824Z > cd server && node ./server.js
2018-04-11T01:16:23.013608724Z 
2018-04-11T01:16:45.311138298Z /home/site/wwwroot/node_modules/natural/lib/natural/classifiers/classifier.js:32
2018-04-11T01:16:45.311426099Z     if (e.code !== 'MODULE_NOT_FOUND') throw e;
2018-04-11T01:16:45.311480799Z                                        ^
2018-04-11T01:16:45.311491899Z 
2018-04-11T01:16:45.311553099Z Error: The module '/home/site/wwwroot/node_modules/webworker-threads/build/Release/WebWorkerThreads.node'
2018-04-11T01:16:45.311560999Z was compiled against a different Node.js version using
2018-04-11T01:16:45.311567599Z NODE_MODULE_VERSION 48. This version of Node.js requires
2018-04-11T01:16:45.311574199Z NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
2018-04-11T01:16:45.311580699Z the module (for instance, using `npm rebuild` or `npm install`).
2018-04-11T01:16:45.311587299Z     at Object.Module._extensions..node (module.js:672:18)
2018-04-11T01:16:45.311593899Z     at Module.load (module.js:556:32)
2018-04-11T01:16:45.311600299Z     at tryModuleLoad (module.js:499:12)
2018-04-11T01:16:45.311606599Z     at Function.Module._load (module.js:491:3)
2018-04-11T01:16:45.311613099Z     at Module.require (module.js:587:17)
2018-04-11T01:16:45.311619599Z     at require (internal/module.js:11:18)
2018-04-11T01:16:45.311625999Z     at bindings (/home/site/wwwroot/node_modules/bindings/bindings.js:81:44)
2018-04-11T01:16:45.311632599Z     at Object.<anonymous> (/home/site/wwwroot/node_modules/webworker-threads/index.js:1:105)
2018-04-11T01:16:45.311639999Z     at Module._compile (module.js:643:30)
2018-04-11T01:16:45.311658499Z     at Object.Module._extensions..js (module.js:654:10)
2018-04-11T01:16:45.311665999Z     at Module.load (module.js:556:32)
2018-04-11T01:16:45.311717699Z     at tryModuleLoad (module.js:499:12)
2018-04-11T01:16:45.311724799Z     at Function.Module._load (module.js:491:3)
2018-04-11T01:16:45.311731099Z     at Module.require (module.js:587:17)
2018-04-11T01:16:45.311737299Z     at require (internal/module.js:11:18)
2018-04-11T01:16:45.311743399Z     at Object.<anonymous> (/home/site/wwwroot/node_modules/natural/lib/natural/classifiers/classifier.js:29:19)
```
